### Site metadata ###

title: Dev Resources
description: Links to tutorials/articles/docs/Wikipedia about programming languages, developers tools and services

github_username: MichaelCurrin

### Build settings ###

url: "https://michaelcurrin.github.io"
baseurl: "/dev-resources"

google_analytics: G-5XEV3CEPK9

header_pages:
  - index.md
  - resources/index.md
  - repos.md
  - about.md

exclude:
  - bin/
  - docs/
  - hooks/
  - vendor/
  - CONTRIBUTING.md
  - Gemfile
  - LICENSE
  - Makefile
  - README.md
  - sample*.png

liquid:
  error_mode: strict

strict_front_matter: true

### Theme boilerplate ###

remote_theme: MichaelCurrin/fractal

titles_from_headings:
  strip_title: true

# All pages except a few top-level pages are resource listings.
defaults:
  - scope:
      path: "resources"
    values:
      layout: "resources"
  - scope:
      path: ""
    values:
      layout: "page"
